name: 'Project CI'

on:
  push:
    branches:
      - main
      - deployment

jobs:
  files-changed:
    runs-on: self-hosted
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Check for folder file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
  deploy-frontend:
    runs-on: self-hosted
    needs: files-changed
    if: needs.files-changed.outputs.frontend == 'true'
    steps:
      - name: Build
        uses: ./.github/workflows/build-frontend.yml
      - name: Deploy
        uses: ./.github/workflows/deploy.yml
        with:
          dockerfile: frontend/deployment/Dockerfile
          context: frontend
          image: swr.ru-moscow-1.hc.sbercloud.ru/geek-battle-2023/frontend
        secrets: inherit
  deploy-backend:
    runs-on: self-hosted
    needs: files-changed
    if: needs.files-changed.outputs.backend == 'true'
    steps:
      - name: Build
        uses: ./.github/workflows/build-backend.yml
      - name: Deploy
        uses: ./.github/workflows/deploy.yml
        with:
          dockerfile: backend/deployment/Dockerfile
          context: backend
          image: swr.ru-moscow-1.hc.sbercloud.ru/geek-battle-2023/backend
        secrets: inherit
