name: 'Project deploy'

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true


jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      HOME: "/root"
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image }}
          tags: |
            type=raw,value=release-{{date 'YYYYMMDD-HHmm'}}-{{sha}}
        
      - name: Login to docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: swr.ru-moscow-1.hc.sbercloud.ru/geek-battle-2023
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy
        run: |
          helm upgrade ${{ inputs.context }} --timeout 2m30s --atomic --history-max=3 --set image.tag=$DOCKER_METADATA_OUTPUT_VERSION ${{ inputs.context }}/deployment

      - name: Clean up
        run: |
          docker rmi $DOCKER_METADATA_OUTPUT_TAGS
          docker builder prune -f

